apiVersion: batch/v1
kind: CronJob
metadata:
  name: withings-garmin-sync
spec:
  schedule: '0 */3 * * *'
  timeZone: "Europe/London" # NeedS k8s >= 1.27. 
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: withings-garmin-sync
              image: ghcr.io/jaroslawhartman/withings-sync:latest
              imagePullPolicy: IfNotPresent

              volumeMounts:
                - mountPath: /data
                  name: oauth-cache

              # Run the container as user 1000 'withings-sync'
              securityContext:
                runAsGroup: 1000
                runAsUser: 1000
              
              command:
                - sh
                - -c
                - |
                  set -eux
                  ln -sf /data/.withings_user.json /home/withings-sync/.withings_user.json
                  ln -sf /data/.garmin_session /home/withings-sync/.garmin_session
                  ls -la /home/withings-sync/
                  poetry run withings-sync --features BLOOD_PRESSURE
              
              envFrom:
                - secretRef:
                    name: withings-secret
          
          volumes:
          - name: oauth-cache
            persistentVolumeClaim:
              claimName: withings-oauth-cache

